// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using person_dogs;

#nullable disable

namespace prueba2.Migrations
{
    [DbContext(typeof(PersonContext))]
    partial class PersonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("person_dogs.Dog", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("AmoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raza")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("AmoId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            id = new Guid("fe2de405-c38e-4c90-ac52-da0540dfbd11"),
                            Age = 5,
                            AmoId = new Guid("fe2de405-c38e-4c90-ac52-da0540dfb4ef"),
                            Nombre = "Chubi"
                        });
                });

            modelBuilder.Entity("person_dogs.Person", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            id = new Guid("fe2de405-c38e-4c90-ac52-da0540dfb4ef"),
                            Apellido = "Corporan",
                            Nombre = "Frandel"
                        });
                });

            modelBuilder.Entity("person_dogs.Dog", b =>
                {
                    b.HasOne("person_dogs.Person", "Amo")
                        .WithMany("dogs")
                        .HasForeignKey("AmoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amo");
                });

            modelBuilder.Entity("person_dogs.Person", b =>
                {
                    b.Navigation("dogs");
                });
#pragma warning restore 612, 618
        }
    }
}
